name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Test on Node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [16, 18, 20]
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build framework
        run: npm run build:all
        
      - name: Run tests (Unix)
        if: runner.os != 'Windows'
        run: npm run test
        
      - name: Run tests (Windows)
        if: runner.os == 'Windows'
        run: npm run test:windows
        
      - name: Check bundle size
        run: |
          echo "## Bundle Size Report 📦" >> $GITHUB_STEP_SUMMARY
          echo "| File | Size |" >> $GITHUB_STEP_SUMMARY
          echo "|------|------|" >> $GITHUB_STEP_SUMMARY
          if [ -f "dist/azhivili-css.css" ]; then
            SIZE=$(du -h dist/azhivili-css.css | cut -f1)
            echo "| azhivili-css.css | $SIZE |" >> $GITHUB_STEP_SUMMARY
          fi
          if [ -f "dist/azhivili-css.min.css" ]; then
            SIZE=$(du -h dist/azhivili-css.min.css | cut -f1)
            echo "| azhivili-css.min.css | $SIZE |" >> $GITHUB_STEP_SUMMARY
          fi
        shell: bash
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}-node${{ matrix.node-version }}
          path: |
            dist/
            !dist/*.map
          retention-days: 7

  security:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run security audit
        run: npm audit --audit-level=moderate
        
      - name: Run dependency check
        uses: ossf/scorecard-action@v2.3.1
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

  quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build framework
        run: npm run build:all
        
      - name: Analyze CSS
        run: |
          echo "## CSS Analysis Report 🎨" >> $GITHUB_STEP_SUMMARY
          echo "### File Statistics" >> $GITHUB_STEP_SUMMARY
          echo "| Metric | Value |" >> $GITHUB_STEP_SUMMARY
          echo "|--------|-------|" >> $GITHUB_STEP_SUMMARY
          
          # Count SCSS files
          SCSS_COUNT=$(find azhivili -name "*.scss" | wc -l)
          echo "| SCSS Files | $SCSS_COUNT |" >> $GITHUB_STEP_SUMMARY
          
          # Count CSS classes (approximate)
          if [ -f "dist/azhivili-css.css" ]; then
            CLASS_COUNT=$(grep -o '\.[a-zA-Z0-9\u0B80-\u0BFF_-]*' dist/azhivili-css.css | sort -u | wc -l)
            echo "| CSS Classes | ~$CLASS_COUNT |" >> $GITHUB_STEP_SUMMARY
          fi
          
          # File sizes
          if [ -f "dist/azhivili-css.css" ]; then
            EXPANDED_SIZE=$(stat -f%z dist/azhivili-css.css 2>/dev/null || stat -c%s dist/azhivili-css.css)
            echo "| Expanded Size | ${EXPANDED_SIZE} bytes |" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ -f "dist/azhivili-css.min.css" ]; then
            MINIFIED_SIZE=$(stat -f%z dist/azhivili-css.min.css 2>/dev/null || stat -c%s dist/azhivili-css.min.css)
            echo "| Minified Size | ${MINIFIED_SIZE} bytes |" >> $GITHUB_STEP_SUMMARY
            
            if [ ! -z "$EXPANDED_SIZE" ] && [ ! -z "$MINIFIED_SIZE" ]; then
              COMPRESSION_RATIO=$(echo "scale=2; $MINIFIED_SIZE * 100 / $EXPANDED_SIZE" | bc)
              echo "| Compression Ratio | ${COMPRESSION_RATIO}% |" >> $GITHUB_STEP_SUMMARY
            fi
          fi
