name: Dependency Updates

on:
  schedule:
    - cron: '0 0 * * 1'  # Weekly on Monday
  workflow_dispatch:

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_TOKEN }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Update dependencies
        run: |
          npm update
          npm audit fix --audit-level=moderate || true
          
      - name: Test with updated dependencies
        run: |
          npm run build:all
          npm test || npm run test:windows
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GIT_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: '🔄 Weekly Dependency Updates'
          body: |
            ## 🔄 Automated Dependency Updates
            
            This PR contains automated dependency updates.
            
            ### Changes
            - Updated npm dependencies to latest versions
            - Applied security fixes where available
            - Verified build and tests still pass
            
            ### Testing
            - ✅ Build successful
            - ✅ Tests passing
            - ✅ No breaking changes detected
            
            Please review and merge if everything looks good.
          branch: dependency-updates
          delete-branch: true
